- name: web server installation
  hosts: web_server
  become: yes
  become_method: sudo
  role: 
      - web.yml

- name: Database server installation
  hosts: database_server
  become: yes
  become_method: sudo
  role: 
      - db.yml
              