- name: web server installation
  hosts: web_server
  become: yes
  become_method: sudo
  roles: 
      - web

- name: Database server installation
  hosts: database_server
  become: yes
  become_method: sudo
  roles: 
      - db
              