- name: anything
  hosts: 172.31.11.118
  become: yes
  become_method: sudo
  tasks:
    - name : yum  mariadb repository add
      yum_repository:
        name: mariadb
        description: MARIADB repository
        file: mariadb
        baseurl: http://yum.mariadb.org/10.3/centos7-amd64
        gpgcheck: yes
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

    - name: install package maraiadb-server and mariadb-client
      yum:
        name: "{{ item }}"
        with_items:
        - mariadb-client
        - maraiadb-server
        state: present