---
# tasks file for web.yml
- name: update all packages
  command: sudo yum update -y

- name: Install apache 
  yum: 
    name: httpd
    state: latest

- name: copy index file to apache 
  copy: 
    src: /Museum_of_Candy/index.html
    dest: /var/www/html/

- name: serive status of httpd
    service: name=httpd state=started enabled=yes